### ISSUE TITLE
Use better error reporter

### ISSUE THREAD

**Issue by shifraHolzer** [qualitybath/io-ts-router#1]
Currently we use the [PathReporter](https://github.com/gcanti/io-ts#error-reporters), which can get very verbose and unreadable when it comes to complex codecs. We should perhaps write a custom Error Reporter that returns clearer and concise messages.

**Comment by shifraHolzer** [comment]
I think were happy with the new reporter... closing.

**Comment by tikotzky** [comment]
![](https://media0.giphy.com/media/4xpB3eE00FfBm/giphy-downsized-medium.gif)

**Comment by shifraHolzer** [comment]
is this a tikotzky child?  😂

**Comment by tikotzky** [comment]
nope https://tineye.com/search/d3aeeb03816f484603624cc96cb49f3df44c5a94?sort=score&order=desc&page=1
